### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by esQmo** [mabahmani/radioamin-android#2]
Any description about this project? Screenshots etc. 
I'm looking for a project I can build from.
Thank you

**Comment by mabahmani** [comment]
Readme Updated!

**Comment by esQmo** [comment]
Thanks. This seems to be a great project! Where does data come from? If I understand it correctly, users that are not logged in will be presented songs from their local storage. But what about logged in users?

**Comment by mabahmani** [comment]
I glad to hear that.
Because its a traning app for my java_backend project at this time data come from my localhost.

You can build my [java-backend project](https://github.com/mabahmani/radioamin-back-java) and communicate with android app.

**Comment by esQmo** [comment]
Thanks. I'll try to adapt your backend to mine
